name: qq_robot_server
description: QQRobot Server
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: 4.0.0
  web_socket_channel: 2.1.0
  html: 0.15.0
  puppeteer: 2.2.0

dev_dependencies:
  test: ^1.16.0
